package net.xqhs.flash.tools.FsmExtractor;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Utility class responsible for bridging the Flash-MAS simulation logs with Formal Verification tools (e.g., EasyLog).
 * <p>
 * This module acts as an HTTP client that communicates with a local Large Language Model (LLM) via Ollama.
 * It takes raw JSON transaction logs generated by the Multi-Agent System, uses "Few-Shot Prompting" to instruct
 * the LLM, and robustly extracts a Finite State Machine (FSM) representation in Graphviz DOT format.
 * <p>
 * <b>Architecture Notes:</b>
 * <ul>
 * <li>Fully compatible with Java 8.</li>
 * <li>Zero external dependencies (avoids Jackson/Gson by using manual JSON payload extraction).</li>
 * <li>Includes bulletproof text sanitization to handle LLM hallucinations or conversational filler.</li>
 * </ul>
 * * @version 1.0
 */
public class LlmFsmExtractor {

    /** * The local endpoint for the Ollama REST API.
     * Assumes Ollama is running on the default localhost port.
     */
    private static final String OLLAMA_API_URL = "http://localhost:11434/api/generate";

    /** * The target model used for inference.
     */
    private static final String MODEL_NAME = "llama3.1";

    /**
     * Main pipeline method. Sends the provided JSON logs to the LLM and extracts the FSM code.
     * * @param jsonLogs The raw JSON string containing the sequence of MAS events (e.g., WAVE_SENT, TRADE_SUCCESS).
     * @return A sanitized string containing exclusively the Graphviz DOT code, or null if the operation fails.
     */
    public static String extractFsmFromJson(String jsonLogs) {
        try {
            /*
             * SYSTEM PROMPT (Few-Shot Prompting Strategy):
             * We provide the LLM with a strict persona, rigid constraints, and a concrete example.
             * This prevents the model from inventing intermediate states and forces it to output raw code.
             */
            String systemPrompt = "Esti un asistent expert in Formal Verification.\\n" +
                    "Sarcina ta este sa analizezi log-urile JSON dintr-un sistem Multi-Agent si sa generezi un FSM in format Graphviz DOT.\\n\\n" +
                    "REGULI DE DESIGN FSM:\\n" +
                    "1. Pastreaza starile simple si la obiect (ex: start, bid_sent, trade_success).\\n" +
                    "2. NU inventa stari intermediare de actiune/procesare.\\n" +
                    "3. Etichetele tranzitiilor (->) trebuie sa reflecte campurile din JSON (ex: WAVE_SENT, TRADE_SUCCESS).\\n" +
                    "4. REGULA ABSOLUTA: Returneaza DOAR codul DOT. Incepe direct cu 'digraph'. Fara nicio explicatie.\\n\\n" +
                    "EXEMPLU DE FORMAT ASTEPTAT:\\n" +
                    "digraph protocol {\\n" +
                    "    node[shape=box, style=filled];\\n" +
                    "    start -> bid_sent [label=\\\"WAVE_SENT\\\"];\\n" +
                    "    bid_sent -> trade_success [label=\\\"TRADE_SUCCESS\\\"];\\n" +
                    "}\\n\\n" +
                    "LOGURI DE ANALIZAT:\\n" + jsonLogs.replace("\"", "\\\"");

            /*
             * REQUEST BODY:
             * 'stream: false' forces Ollama to return the entire response in a single JSON package.
             * 'temperature: 0.0' forces the model to be highly deterministic, removing creative variations.
             */
            String requestBody = String.format(
                    "{\"model\": \"%s\", \"prompt\": \"%s\", \"stream\": false, \"options\": {\"temperature\": 0.0}}",
                    MODEL_NAME, systemPrompt
            );

            // Establish standard HTTP connection (Java 8 compliant)
            URL url = new URL(OLLAMA_API_URL);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Accept", "application/json");
            con.setDoOutput(true);

            System.out.println("[LLM Extractor] Transmitting data to " + MODEL_NAME + " for FSM inference...");

            // Write the JSON payload to the connection stream
            try(OutputStream os = con.getOutputStream()) {
                os.write(requestBody.getBytes(StandardCharsets.UTF_8));
            }

            // Guard clause: Ensure the API processed the request successfully
            if (con.getResponseCode() != 200) {
                System.err.println("[LLM Extractor Error] HTTP Response Code: " + con.getResponseCode());
                return null;
            }

            // Buffer the incoming HTTP response
            StringBuilder response = new StringBuilder();
            try(BufferedReader br = new BufferedReader(
                    new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8))) {
                String line;
                while ((line = br.readLine()) != null) {
                    response.append(line.trim());
                }
            }

            // Process the response: 1. Extract JSON -> 2. Sanitize DOT bounds
            String rawLlmText = extractResponseText(response.toString());
            return sanitizeDotOutput(rawLlmText);

        } catch (Exception e) {
            System.err.println("[LLM Extractor Error] Exception during LLM inference: " + e.getMessage());
            return null;
        }
    }

    /**
     * Persists the generated FSM content to the local filesystem.
     * * @param content  The DOT code to save.
     * @param fileName The desired path and filename (e.g., "protocol.fsm").
     */
    public static void saveToFile(String content, String fileName) {
        try {
            Files.write(Paths.get(fileName), content.getBytes(StandardCharsets.UTF_8));
            System.out.println("[LLM Extractor] Successfully exported FSM to: " + fileName);
        } catch (Exception e) {
            System.err.println("[LLM Extractor Error] Failed to write file: " + e.getMessage());
        }
    }

    /**
     * Manually extracts the value of the "response" field from the Ollama JSON envelope.
     * This method avoids the need for heavy JSON libraries (like Jackson/Gson) to maintain a lightweight footprint.
     * * @param json The complete HTTP JSON response from Ollama.
     * @return The raw text generated by the LLM, with escaped characters resolved.
     */
    private static String extractResponseText(String json) {
        String key = "\"response\":\"";
        int start = json.indexOf(key);
        if (start == -1) return json; // Fallback if format changes
        start += key.length();

        int end = start;
        // Search for the terminating quote, ignoring quotes that are escaped inside the text
        while (end < json.length()) {
            if (json.charAt(end) == '"' && json.charAt(end - 1) != '\\') break;
            end++;
        }

        if (end == json.length()) return json;

        // Unescape standard JSON formatting characters and unicode symbols
        return json.substring(start, end)
                .replace("\\n", "\n")
                .replace("\\t", "\t")
                .replace("\\\"", "\"")
                .replace("\\\\", "\\")
                .replace("\\u003e", ">"); // Restore Graphviz transition arrows
    }

    /**
     * Post-processing sanitizer that guarantees the output is strictly valid DOT syntax.
     * It scans the LLM output, locates the 'digraph' keyword, and truncates everything after the final '}'.
     * This protects the pipeline from LLMs that generate conversational filler text (yapping).
     * * @param input The raw unescaped text from the LLM.
     * @return A clean, Graphviz-ready string.
     */
    private static String sanitizeDotOutput(String input) {
        if (input == null) return null;

        int startIndex = input.indexOf("digraph");
        if (startIndex == -1) {
            System.err.println("[LLM Extractor Warning] The keyword 'digraph' was not found in the output.");
            return input.trim();
        }

        int endIndex = input.lastIndexOf("}");
        if (endIndex == -1 || endIndex < startIndex) {
            System.err.println("[LLM Extractor Warning] Closing brace '}' was not found in the output.");
            return input.trim();
        }

        return input.substring(startIndex, endIndex + 1);
    }
}