package net.xqhs.flash.tools.player;

import net.xqhs.flash.FlashBoot;
import net.xqhs.flash.core.recorder.SimulationEvent;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * MultiAgentReplayer - The core engine coordinating the Hybrid Simulation.
 * <p>
 * This class handles fast-forwarding to historical states, dynamically generating
 * XML deployment configurations, and injecting historical events into Mocked agents
 * while letting Live agents execute natively.
 * </p>
 */
public class MultiAgentReplayer implements Runnable {

    /** Memory bridge used to restore agent internal states before hot-swapping. */
    public static final Map<String, Object> SharedStateBridge = new ConcurrentHashMap<>();

    /** Real-time queue capturing events generated by native Live agents. */
    public static final Queue<SimulationEvent> LiveEventStream = new ConcurrentLinkedQueue<>();

    /** Registry of currently running agent instances (Mocked). */
    private static final Map<String, MockAgent> runningInstances = new ConcurrentHashMap<>();

    private final List<SimulationEvent> events;
    private final Map<String, String> agentModes;
    private final Map<String, String> agentRegistry;

    private final AtomicInteger currentIndex = new AtomicInteger(0);
    private final AtomicBoolean isRunning = new AtomicBoolean(false);
    private final AtomicBoolean isPaused = new AtomicBoolean(true);

    private Thread flashMasThread;
    private double timeScale = 1.0;

    public MultiAgentReplayer(List<SimulationEvent> events, int startIndex, Map<String, String> modes, Map<String, String> registry) {
        this.events = events;
        this.currentIndex.set(startIndex);
        this.agentModes = modes != null ? modes : new HashMap<>();
        this.agentRegistry = new HashMap<>();
    }

    public static void registerAgentInstance(String name, MockAgent agent) {
        if (name != null) runningInstances.put(name, agent);
    }

    @Override
    public void run() {
        try {
            System.out.println("[Replayer] Initiating state recovery (Fast-Forwarding)...");
            recoverSystemState();

            System.out.println("[Replayer] Booting native Flash-MAS runtime...");
            bootFlashMAS();

            isRunning.set(true);
            isPaused.set(false);

            while (isRunning.get() && currentIndex.get() < events.size()) {
                if (isPaused.get()) {
                    Thread.sleep(100);
                    continue;
                }

                SimulationEvent event = events.get(currentIndex.get());
                String entityName = event.getEntityName();

                // Prevent infinite system loops by ignoring pylon infrastructure events
                if (entityName != null && !entityName.equals("local") && !entityName.toLowerCase().contains("pylon")) {
                    MockAgent agent = runningInstances.get(entityName);

                    // If agent is set to Mocked, force it to execute its historical step
                    if (agent != null && !"live".equals(agentModes.get(entityName))) {
                        agent.executeHistoricalStep(event);
                    }
                }

                waitForNextStep();
                currentIndex.incrementAndGet();
            }
        } catch (InterruptedException e) {
            System.out.println("[Replayer] Execution halted for dynamic Hot-Swap.");
        } catch (Exception e) {
            System.err.println("[Replayer] Critical runtime exception: " + e.getMessage());
            e.printStackTrace();
        } finally {
            isRunning.set(false);
        }
    }

    /**
     * Scans the log to identify agent classes and restore states up to the starting index.
     */
    private void recoverSystemState() {
        SharedStateBridge.clear();
        LiveEventStream.clear();

        // 1. Foolproof Class Scanner (Actor Isolation & Fallbacks)
        for (SimulationEvent ev : events) {
            if ("AGENT_START".equals(ev.getType()) && ev.getEntityName() != null) {
                Object payload = ev.getPayload();
                String extractedClass = null;

                if (payload instanceof List && !((List<?>) payload).isEmpty()) {
                    extractedClass = ((List<?>) payload).get(0).toString();
                } else if (payload instanceof String) {
                    extractedClass = payload.toString();
                } else if (payload instanceof Object[] && ((Object[])payload).length > 0) {
                    extractedClass = ((Object[])payload)[0].toString();
                }

                if (extractedClass != null) {
                    // Fail-safe: Update legacy class paths automatically if needed
                    if (extractedClass.startsWith("example.energyMarket")) {
                        extractedClass = extractedClass.replace("example.energyMarket", "Tiberiu.energyMarket");
                    }
                    agentRegistry.put(ev.getEntityName(), extractedClass);
                }
            }
        }

        System.out.println("[Replayer] Discovered classes for native boot: " + agentRegistry);

        // 2. Fast-Forward State Preparation
        for (int i = 0; i < currentIndex.get(); i++) {
            SimulationEvent ev = events.get(i);
            if (ev.getEntityName() != null && (ev.getType().contains("STATE") || ev.getType().contains("UPDATE"))) {
                SharedStateBridge.put(ev.getEntityName() + "_state", ev.getPayload());
            }
        }
    }

    /**
     * Generates a temporary XML config and launches the Flash-MAS engine.
     */
    private void bootFlashMAS() throws Exception {
        String xml = HybridBootstrapper.prepareDeployment(agentModes, agentRegistry);
        File tempDeployment = new File("hybrid_deployment.xml");
        Files.write(tempDeployment.toPath(), xml.getBytes(StandardCharsets.UTF_8));
        tempDeployment.deleteOnExit();

        flashMasThread = new Thread(() -> {
            try { FlashBoot.main(new String[] { tempDeployment.getName() }); }
            catch (Exception e) { System.out.println("[Replayer] Flash-MAS native thread terminated."); }
        }, "FlashMAS-Main-Thread");

        flashMasThread.start();
        Thread.sleep(3000); // Allow shards and pylons to mount
    }

    /**
     * Maintains correct simulation tempo using micro-sleeping for UI responsiveness.
     */
    private void waitForNextStep() throws InterruptedException {
        int idx = currentIndex.get();
        if (idx + 1 < events.size()) {
            long delta = events.get(idx + 1).getTimestamp() - events.get(idx).getTimestamp();
            if (delta > 0) {
                long waitTime = (long) (delta / timeScale);
                long startWait = System.currentTimeMillis();

                // Micro-sleeping ensures pause/stop requests are handled instantly
                while (System.currentTimeMillis() - startWait < waitTime) {
                    if (!isRunning.get() || isPaused.get()) break;
                    Thread.sleep(10);
                }
            }
        } else {
            Thread.sleep(100);
        }
    }

    public List<SimulationEvent> consumeLiveEvents() {
        List<SimulationEvent> chunk = new ArrayList<>();
        SimulationEvent ev;
        while ((ev = LiveEventStream.poll()) != null) chunk.add(ev);
        return chunk;
    }

    public void setTimeScale(double scale) { this.timeScale = scale; }
    public Map<String, String> getAgentModes() { return agentModes; }
    public Map<String, String> getAgentRegistry() { return agentRegistry; }

    public void pause() { isPaused.set(true); }
    public void resume() { isPaused.set(false); }
    public int getCurrentIndex() { return currentIndex.get(); }
    public boolean isPlaying() { return isRunning.get() && !isPaused.get(); }

    /**
     * Safely terminates the native runtime to prevent memory leaks during reloads.
     */
    public void stop() {
        isRunning.set(false);
        if (flashMasThread != null && flashMasThread.isAlive()) {
            flashMasThread.interrupt();
            System.out.println("[Replayer] Flash-MAS native thread interrupted cleanly.");
        }
    }
}