MODELS:
- class_names:
  - apple
  - atm card
  - cat
  - banana
  - bangle
  - battery
  - bottle
  - broom
  - bulb
  - calender
  - camera
  cuda: true
  input_size:
  - 224
  - 224
  input_space: RGB
  name: ResNet18
  normalization:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  operation_module: imageInput
  path: ml-directory/models/resnet18.pth
  transform: true
