MODELS:
  # - name: "MobileNetV2"
  #   path: "ml-directory/models/mobilenetv2.pth"
  #   transform: "datasets.transform.ImageNetTransform"
  #   cuda: false
  #   input_space: RGB
  #   task: "classification"
  #   dataset: "ImageNet"

  - name: "CombinedModel"
    code: "net.xqhs.flash.ml.python_module.combined_model_entry"
    cuda: false

DATASETS: []
