name: Generate HTML directly in Repo

on:
  push:
    branches:
      - master
      - documentation
    # Ignore commits made by bot
    paths-ignore:
      - 'public/**'
  workflow_dispatch:

permissions:
  contents: write  # script has access to write in repo

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Prepare Output Folder
        run: |
          mkdir -p public
          cp -r doc/* public/
          cp README.md public/index.md
          cp CONTRIBUTORS.md public/CONTRIBUTORS.md
          cp -r identity public/

      - name: Convert MD to HTML
        run: |
          find public -name "*.md" | while read file; do
            echo "Converting $file..."
          
            # Save the new html file name in html_file
            html_file="${file%.md}.html"
          
            pandoc "$file" -o "$html_file" --standalone --metadata title="Documentation"
            rm "$file"
          
            # Transforms "doc/name.md" into "name.html"
            sed -i 's|doc/\(.*\)\.md|\1.html|g' "$html_file"
          
            # Transforms rest of ".md" files into ".html"
            sed -i 's|\.md|.html|g' "$html_file"
          done

      - name: Commit and Push changes
        run: |
          # Configure Bot
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
          git add public/
          
          # Verify if there are changes before commit
          if git diff --staged --quiet; then
            echo "No change in documentation."
          else
            git commit -m "Auto-generated HTML documentation [skip ci]"
            git push
          fi